name: Descent 3 Build

on:
  workflow_dispatch:
  push:
    branches: [ "*" ]
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'

jobs:
  build:
    name: ${{ matrix.os.name }}, ${{ matrix.build_type }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - runner: macos-14
            preset: mac
            cc: cc
            cxx: c++
            name: macOS-Intel
        build_type:
          - Debug

    runs-on: ${{ matrix.os.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Install macOS dependencies
        if: ${{ matrix.os.preset == 'mac' }}
        run: |
          # Install packages from Homebrew
          brew bundle install

      - name: Install Linux dependencies
        if: ${{ matrix.os.preset == 'linux' }}
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            ninja-build cmake g++ libgtest-dev libsdl2-dev zlib1g-dev libspdlog-dev

      - name: Install Windows dependencies
        if: ${{ matrix.os.runner == 'windows-latest' }}
        run: choco install ninja
      
      - uses: ilammy/msvc-dev-cmd@v1
        if: ${{ matrix.os.runner == 'windows-latest' }}
        with:
           arch: win64

      - name: Configure CMake
        env:
          CC: ${{ matrix.os.cc }}
          CXX: ${{ matrix.os.cxx }}
          VCPKG_ROOT: C:/vcpkg
        run: cmake --preset ${{ matrix.os.preset }} -DBUILD_TESTING=ON -DENABLE_LOGGER=ON -DFORCE_PORTABLE_INSTALL=ON -DBUILD_EDITOR=ON

      - name: Build ${{ matrix.build_type }}
        run: cmake --build --preset ${{ matrix.os.preset }} --config ${{ matrix.build_type }} --verbose

      - name: Run ${{ matrix.build_type }} Unittests
        run: ctest -VV --preset ${{ matrix.os.preset }} -C ${{ matrix.build_type }}

      - name: Local install
        # There no cmake install presets so install in traditional way
        run: cmake --install builds/${{ matrix.os.preset }}/ --config ${{ matrix.build_type }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Descent3_${{ matrix.build_type }}_${{ matrix.os.name }}
          path: ${{ github.workspace }}/builds/${{ matrix.os.preset }}/installed/
